spring.application.name=SeoulBikeAnalytics

mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.metanet.seoulbike.test.dto

file.upload-dir=./upload-files/

# 최대 파일 크기 설정
spring.servlet.multipart.max-file-size=500MB

# 한 번의 HTTP 요청에 담길 수 있는 전체 크기
spring.servlet.multipart.max-request-size=500MB

# (선택) 임시 저장 경로 설정 (메모리 부족 방지)
# 파일이 설정값보다 크면 디스크에 임시 파일을 생성
spring.servlet.multipart.file-size-threshold=2KB

spring.messages.basename=i18n/message
spring.messages.encoding=UTF-8
