spring.application.name=SeoulBikeAnalytics

mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=com.metanet.seoulbike


# File Storage
file.storage.root-path=/upload-files
file.storage.archive-path=${file.storage.root-path}/archive
file.storage.attachment-path=${file.storage.root-path}/attachments


# \ucd5c\ub300 \ud30c\uc77c \ud06c\uae30 \uc124\uc815
spring.servlet.multipart.max-file-size=500MB

# \ud55c \ubc88\uc758 HTTP \uc694\uccad\uc5d0 \ub2f4\uae38 \uc218 \uc788\ub294 \uc804\uccb4 \ud06c\uae30
spring.servlet.multipart.max-request-size=500MB

# (\uc120\ud0dd) \uc784\uc2dc \uc800\uc7a5 \uacbd\ub85c \uc124\uc815 (\uba54\ubaa8\ub9ac \ubd80\uc871 \ubc29\uc9c0)
# \ud30c\uc77c\uc774 \uc124\uc815\uac12\ubcf4\ub2e4 \ud06c\uba74 \ub514\uc2a4\ud06c\uc5d0 \uc784\uc2dc \ud30c\uc77c\uc744 \uc0dd\uc131
spring.servlet.multipart.file-size-threshold=2KB

spring.messages.basename=i18n/message
spring.messages.encoding=UTF-8
