spring.application.name=SeoulBikeAnalytics

mybatis.configuration.map-underscore-to-camel-case=true

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=hr
spring.datasource.password=hr

mybatis.mapper-locations=classpath:mapper/**/*.xml

mybatis.type-aliases-package=com.metanet.seoulbike

file.upload-dir=./upload-files/

spring.servlet.multipart.max-file-size=500MB

spring.servlet.multipart.max-request-size=500MB

spring.servlet.multipart.file-size-threshold=2KB

spring.messages.basename=i18n/message
spring.messages.encoding=UTF-8
